### PR TITLE
Fix Println typos in Basics section

### PR DESCRIPTION
**Pull request by marvelousNinja**
Subtle change in Chapter 1 - Basics.

### CODE REVIEW

**Comment by karlseguin** [comment]
Why would `println` be PascalCase?  all the builtin functions are fully uppercase.

Also, there's nothing wrong with using `fmt.Printf`

**Comment by karlseguin** [comment]
:+1:

**Comment by marvelousNinja** [comment]
Perhaps I misunderstood context, but in every piece of code around ```fmt.Println``` is used. Perhaps very first code snippets should be changed to use actual built-in function.

However, there're references like this:
> You’ve probably noticed we prefix the function name with the package, e.g., fmt.Printf.


> You can head over to http://golang.org/pkg/fmt/#Printf to learn more about the Printf function that we used.

So I was merely trying to fix a confusion here (since Printf and Println is not the same thing).

**Comment by karlseguin** [comment]
thanks

**Pull request merged**
